/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: Principal;
    profilePicUrl?: string;
    verified: boolean;
    name: string;
    createdAt: Time;
    phone: string;
    followers: bigint;
    location: string;
    highestRating: bigint;
}
export type Time = bigint;
export interface BoostOption {
    durationDays: bigint;
    priceGMD: bigint;
}
export interface AnonMessage {
    id: MessageId;
    content: string;
    listingId: ListingId;
    receiverId: Principal;
    timestamp: Time;
    senderName: string;
    senderId?: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: ReportId;
    status: string;
    reportedId: Principal;
    reporterId: Principal;
    reason: string;
}
export interface Transaction {
    id: TransactionId;
    status: string;
    paymentMethod: string;
    listingId: ListingId;
    buyerId: Principal;
    sellerId: Principal;
    amount: bigint;
}
export type ReportId = bigint;
export type TransactionId = bigint;
export type ListingId = bigint;
export type MessageId = bigint;
export interface Message {
    id: MessageId;
    isDeleted: boolean;
    content: string;
    listingId: ListingId;
    receiverId: Principal;
    isEdited: boolean;
    timestamp: Time;
    senderId: Principal;
}
export interface PublicListing {
    id: ListingId;
    status: string;
    subCategory?: RealEstateSubCategory;
    title: string;
    numBedrooms?: bigint;
    propertySize?: bigint;
    createdAt: Time;
    isFurnished?: boolean;
    description: string;
    isBoosted: boolean;
    category: ListingCategory;
    boostExpiry?: Time;
    sellerId: Principal;
    price: bigint;
    location: string;
    photos: Array<ExternalBlob>;
    condition: string;
}
export type ReviewId = bigint;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Review {
    id: ReviewId;
    listingId: ListingId;
    createdAt: Time;
    revieweeId: Principal;
    reviewerId: Principal;
    comment: string;
    stars: bigint;
}
export enum ListingCategory {
    clothing = "clothing",
    laptops = "laptops",
    realEstate = "realEstate",
    other = "other",
    pets = "pets",
    furniture = "furniture",
    bicycles = "bicycles",
    shoes = "shoes",
    spareParts = "spareParts",
    carsAndTrucks = "carsAndTrucks",
    beauty = "beauty",
    motorcycles = "motorcycles",
    appliances = "appliances",
    fashion = "fashion",
    services = "services",
    electronics = "electronics",
    phones = "phones",
    health = "health"
}
export enum RealEstateSubCategory {
    apartmentsAndFlats = "apartmentsAndFlats",
    landAndProperties = "landAndProperties",
    commercialSpaces = "commercialSpaces",
    housesForRent = "housesForRent",
    housesForSale = "housesForSale",
    shortLetHolidayRentals = "shortLetHolidayRentals"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAllowedCategory(category: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(title: string, description: string, category: ListingCategory, subCategory: RealEstateSubCategory | null, price: bigint, condition: string, photos: Array<ExternalBlob>, location: string, propertySize: bigint | null, numBedrooms: bigint | null, isFurnished: boolean | null): Promise<ListingId>;
    createOrUpdateUserProfile(name: string, location: string): Promise<void>;
    createReport(reportedId: Principal, reason: string): Promise<ReportId>;
    createReview(revieweeId: Principal, listingId: ListingId, stars: bigint, comment: string): Promise<ReviewId>;
    createTransaction(listingId: ListingId, sellerId: Principal, paymentMethod: string, amount: bigint): Promise<TransactionId>;
    deleteListing(listingId: ListingId): Promise<void>;
    deleteMessage(messageId: MessageId): Promise<void>;
    editMessage(messageId: MessageId, newContent: string): Promise<void>;
    followSeller(sellerId: Principal): Promise<void>;
    getAllCategories(): Promise<Array<string>>;
    getAllListings(): Promise<Array<PublicListing>>;
    getAllReports(): Promise<Array<Report>>;
    getAnonymousMessageById(messageId: MessageId): Promise<AnonMessage | null>;
    getBoostOptions(): Promise<Array<BoostOption>>;
    getBoostedListings(): Promise<Array<PublicListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFollowers(sellerId: Principal): Promise<Array<Principal>>;
    getFollowing(): Promise<Array<Principal>>;
    getLikedListings(): Promise<Array<ListingId>>;
    getListing(listingId: ListingId): Promise<PublicListing | null>;
    getListingsByCategory(category: ListingCategory): Promise<Array<PublicListing>>;
    getMessagesForListing(listingId: ListingId): Promise<Array<Message>>;
    getMyConversations(): Promise<Array<Message>>;
    getMyListings(): Promise<Array<PublicListing>>;
    getReviewsForUser(userId: Principal): Promise<Array<Review>>;
    getTransaction(txId: TransactionId): Promise<Transaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    likeListing(listingId: ListingId): Promise<boolean>;
    likeListingAnon(listingId: ListingId): Promise<boolean>;
    removeAllowedCategory(category: string): Promise<void>;
    saveCallerUserProfile(name: string, phone: string, location: string): Promise<void>;
    searchListings(searchText: string): Promise<Array<PublicListing>>;
    sendMessage(listingId: ListingId, receiverId: Principal, content: string): Promise<MessageId>;
    sendMessageAnon(senderName: string, messageText: string, listingId: ListingId, receiverId: Principal): Promise<MessageId>;
    setListingBoosted(listingId: ListingId, isBoosted: boolean, durationDays: bigint): Promise<void>;
    unfollowSeller(sellerId: Principal): Promise<void>;
    updateAllUserProfilesWithHighestRating(): Promise<void>;
    updateListing(listingId: ListingId, title: string, description: string, category: ListingCategory, subCategory: RealEstateSubCategory | null, price: bigint, condition: string, photos: Array<ExternalBlob>, location: string, propertySize: bigint | null, numBedrooms: bigint | null, isFurnished: boolean | null): Promise<void>;
    updateListingStatus(listingId: ListingId, status: string): Promise<void>;
    updateProfilePic(url: string): Promise<void>;
    updateReportStatus(reportId: ReportId, status: string): Promise<void>;
    updateTransactionStatus(txId: TransactionId, status: string): Promise<void>;
}
import type { AnonMessage as _AnonMessage, ExternalBlob as _ExternalBlob, ListingCategory as _ListingCategory, ListingId as _ListingId, MessageId as _MessageId, PublicListing as _PublicListing, RealEstateSubCategory as _RealEstateSubCategory, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAllowedCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllowedCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllowedCategory(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: ListingCategory, arg3: RealEstateSubCategory | null, arg4: bigint, arg5: string, arg6: Array<ExternalBlob>, arg7: string, arg8: bigint | null, arg9: bigint | null, arg10: boolean | null): Promise<ListingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(arg0, arg1);
            return result;
        }
    }
    async createReport(arg0: Principal, arg1: string): Promise<ReportId> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0, arg1);
            return result;
        }
    }
    async createReview(arg0: Principal, arg1: ListingId, arg2: bigint, arg3: string): Promise<ReviewId> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTransaction(arg0: ListingId, arg1: Principal, arg2: string, arg3: bigint): Promise<TransactionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteListing(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async editMessage(arg0: MessageId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, arg1);
            return result;
        }
    }
    async followSeller(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followSeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followSeller(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllListings(): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return result;
        }
    }
    async getAnonymousMessageById(arg0: MessageId): Promise<AnonMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnonymousMessageById(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnonymousMessageById(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoostOptions(): Promise<Array<BoostOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoostOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoostOptions();
            return result;
        }
    }
    async getBoostedListings(): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoostedListings();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoostedListings();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowing(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing();
            return result;
        }
    }
    async getLikedListings(): Promise<Array<ListingId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikedListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikedListings();
            return result;
        }
    }
    async getListing(arg0: ListingId): Promise<PublicListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingsByCategory(arg0: ListingCategory): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingsByCategory(to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingsByCategory(to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForListing(arg0: ListingId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForListing(arg0);
            return result;
        }
    }
    async getMyConversations(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConversations();
            return result;
        }
    }
    async getMyListings(): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForUser(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForUser(arg0);
            return result;
        }
    }
    async getTransaction(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeListing(arg0: ListingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeListing(arg0);
            return result;
        }
    }
    async likeListingAnon(arg0: ListingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeListingAnon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeListingAnon(arg0);
            return result;
        }
    }
    async removeAllowedCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAllowedCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAllowedCategory(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<PublicListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: ListingId, arg1: Principal, arg2: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async sendMessageAnon(arg0: string, arg1: string, arg2: ListingId, arg3: Principal): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageAnon(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageAnon(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setListingBoosted(arg0: ListingId, arg1: boolean, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setListingBoosted(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setListingBoosted(arg0, arg1, arg2);
            return result;
        }
    }
    async unfollowSeller(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowSeller(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowSeller(arg0);
            return result;
        }
    }
    async updateAllUserProfilesWithHighestRating(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAllUserProfilesWithHighestRating();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAllUserProfilesWithHighestRating();
            return result;
        }
    }
    async updateListing(arg0: ListingId, arg1: string, arg2: string, arg3: ListingCategory, arg4: RealEstateSubCategory | null, arg5: bigint, arg6: string, arg7: Array<ExternalBlob>, arg8: string, arg9: bigint | null, arg10: bigint | null, arg11: boolean | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, to_candid_ListingCategory_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async updateListingStatus(arg0: ListingId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingStatus(arg0, arg1);
            return result;
        }
    }
    async updateProfilePic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePic(arg0);
            return result;
        }
    }
    async updateReportStatus(arg0: ReportId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportStatus(arg0, arg1);
            return result;
        }
    }
    async updateTransactionStatus(arg0: TransactionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AnonMessage_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnonMessage): AnonMessage {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingCategory): ListingCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicListing_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicListing): Promise<PublicListing> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RealEstateSubCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RealEstateSubCategory): RealEstateSubCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RealEstateSubCategory]): RealEstateSubCategory | null {
    return value.length === 0 ? null : from_candid_RealEstateSubCategory_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnonMessage]): AnonMessage | null {
    return value.length === 0 ? null : from_candid_AnonMessage_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicListing]): Promise<PublicListing | null> {
    return value.length === 0 ? null : await from_candid_PublicListing_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    status: string;
    subCategory: [] | [_RealEstateSubCategory];
    title: string;
    numBedrooms: [] | [bigint];
    propertySize: [] | [bigint];
    createdAt: _Time;
    isFurnished: [] | [boolean];
    description: string;
    isBoosted: boolean;
    category: _ListingCategory;
    boostExpiry: [] | [_Time];
    sellerId: Principal;
    price: bigint;
    location: string;
    photos: Array<_ExternalBlob>;
    condition: string;
}): Promise<{
    id: ListingId;
    status: string;
    subCategory?: RealEstateSubCategory;
    title: string;
    numBedrooms?: bigint;
    propertySize?: bigint;
    createdAt: Time;
    isFurnished?: boolean;
    description: string;
    isBoosted: boolean;
    category: ListingCategory;
    boostExpiry?: Time;
    sellerId: Principal;
    price: bigint;
    location: string;
    photos: Array<ExternalBlob>;
    condition: string;
}> {
    return {
        id: value.id,
        status: value.status,
        subCategory: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.subCategory)),
        title: value.title,
        numBedrooms: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.numBedrooms)),
        propertySize: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.propertySize)),
        createdAt: value.createdAt,
        isFurnished: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.isFurnished)),
        description: value.description,
        isBoosted: value.isBoosted,
        category: from_candid_ListingCategory_n25(_uploadFile, _downloadFile, value.category),
        boostExpiry: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.boostExpiry)),
        sellerId: value.sellerId,
        price: value.price,
        location: value.location,
        photos: await from_candid_vec_n28(_uploadFile, _downloadFile, value.photos),
        condition: value.condition
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    listingId: _ListingId;
    receiverId: Principal;
    timestamp: _Time;
    senderName: string;
    senderId: [] | [Principal];
}): {
    id: MessageId;
    content: string;
    listingId: ListingId;
    receiverId: Principal;
    timestamp: Time;
    senderName: string;
    senderId?: Principal;
} {
    return {
        id: value.id,
        content: value.content,
        listingId: value.listingId,
        receiverId: value.receiverId,
        timestamp: value.timestamp,
        senderName: value.senderName,
        senderId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.senderId))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    profilePicUrl: [] | [string];
    verified: boolean;
    name: string;
    createdAt: _Time;
    phone: string;
    followers: bigint;
    location: string;
    highestRating: bigint;
}): {
    id: Principal;
    profilePicUrl?: string;
    verified: boolean;
    name: string;
    createdAt: Time;
    phone: string;
    followers: bigint;
    location: string;
    highestRating: bigint;
} {
    return {
        id: value.id,
        profilePicUrl: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.profilePicUrl)),
        verified: value.verified,
        name: value.name,
        createdAt: value.createdAt,
        phone: value.phone,
        followers: value.followers,
        location: value.location,
        highestRating: value.highestRating
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apartmentsAndFlats: null;
} | {
    landAndProperties: null;
} | {
    commercialSpaces: null;
} | {
    housesForRent: null;
} | {
    housesForSale: null;
} | {
    shortLetHolidayRentals: null;
}): RealEstateSubCategory {
    return "apartmentsAndFlats" in value ? RealEstateSubCategory.apartmentsAndFlats : "landAndProperties" in value ? RealEstateSubCategory.landAndProperties : "commercialSpaces" in value ? RealEstateSubCategory.commercialSpaces : "housesForRent" in value ? RealEstateSubCategory.housesForRent : "housesForSale" in value ? RealEstateSubCategory.housesForSale : "shortLetHolidayRentals" in value ? RealEstateSubCategory.shortLetHolidayRentals : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    laptops: null;
} | {
    realEstate: null;
} | {
    other: null;
} | {
    pets: null;
} | {
    furniture: null;
} | {
    bicycles: null;
} | {
    shoes: null;
} | {
    spareParts: null;
} | {
    carsAndTrucks: null;
} | {
    beauty: null;
} | {
    motorcycles: null;
} | {
    appliances: null;
} | {
    fashion: null;
} | {
    services: null;
} | {
    electronics: null;
} | {
    phones: null;
} | {
    health: null;
}): ListingCategory {
    return "clothing" in value ? ListingCategory.clothing : "laptops" in value ? ListingCategory.laptops : "realEstate" in value ? ListingCategory.realEstate : "other" in value ? ListingCategory.other : "pets" in value ? ListingCategory.pets : "furniture" in value ? ListingCategory.furniture : "bicycles" in value ? ListingCategory.bicycles : "shoes" in value ? ListingCategory.shoes : "spareParts" in value ? ListingCategory.spareParts : "carsAndTrucks" in value ? ListingCategory.carsAndTrucks : "beauty" in value ? ListingCategory.beauty : "motorcycles" in value ? ListingCategory.motorcycles : "appliances" in value ? ListingCategory.appliances : "fashion" in value ? ListingCategory.fashion : "services" in value ? ListingCategory.services : "electronics" in value ? ListingCategory.electronics : "phones" in value ? ListingCategory.phones : "health" in value ? ListingCategory.health : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicListing>): Promise<Array<PublicListing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PublicListing_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): _ListingCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RealEstateSubCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RealEstateSubCategory): _RealEstateSubCategory {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RealEstateSubCategory | null): [] | [_RealEstateSubCategory] {
    return value === null ? candid_none() : candid_some(to_candid_RealEstateSubCategory_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingCategory): {
    clothing: null;
} | {
    laptops: null;
} | {
    realEstate: null;
} | {
    other: null;
} | {
    pets: null;
} | {
    furniture: null;
} | {
    bicycles: null;
} | {
    shoes: null;
} | {
    spareParts: null;
} | {
    carsAndTrucks: null;
} | {
    beauty: null;
} | {
    motorcycles: null;
} | {
    appliances: null;
} | {
    fashion: null;
} | {
    services: null;
} | {
    electronics: null;
} | {
    phones: null;
} | {
    health: null;
} {
    return value == ListingCategory.clothing ? {
        clothing: null
    } : value == ListingCategory.laptops ? {
        laptops: null
    } : value == ListingCategory.realEstate ? {
        realEstate: null
    } : value == ListingCategory.other ? {
        other: null
    } : value == ListingCategory.pets ? {
        pets: null
    } : value == ListingCategory.furniture ? {
        furniture: null
    } : value == ListingCategory.bicycles ? {
        bicycles: null
    } : value == ListingCategory.shoes ? {
        shoes: null
    } : value == ListingCategory.spareParts ? {
        spareParts: null
    } : value == ListingCategory.carsAndTrucks ? {
        carsAndTrucks: null
    } : value == ListingCategory.beauty ? {
        beauty: null
    } : value == ListingCategory.motorcycles ? {
        motorcycles: null
    } : value == ListingCategory.appliances ? {
        appliances: null
    } : value == ListingCategory.fashion ? {
        fashion: null
    } : value == ListingCategory.services ? {
        services: null
    } : value == ListingCategory.electronics ? {
        electronics: null
    } : value == ListingCategory.phones ? {
        phones: null
    } : value == ListingCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RealEstateSubCategory): {
    apartmentsAndFlats: null;
} | {
    landAndProperties: null;
} | {
    commercialSpaces: null;
} | {
    housesForRent: null;
} | {
    housesForSale: null;
} | {
    shortLetHolidayRentals: null;
} {
    return value == RealEstateSubCategory.apartmentsAndFlats ? {
        apartmentsAndFlats: null
    } : value == RealEstateSubCategory.landAndProperties ? {
        landAndProperties: null
    } : value == RealEstateSubCategory.commercialSpaces ? {
        commercialSpaces: null
    } : value == RealEstateSubCategory.housesForRent ? {
        housesForRent: null
    } : value == RealEstateSubCategory.housesForSale ? {
        housesForSale: null
    } : value == RealEstateSubCategory.shortLetHolidayRentals ? {
        shortLetHolidayRentals: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
